<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lowongan</name>
   <tag></tag>
   <elementGuidId>8ed24273-9782-4a63-a75a-795cde2b7174</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#job_vacancy > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='job_vacancy']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Lowongan&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>418df271-65ce-493e-b548-dfb8c936c2fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>main#job_vacancy</value>
      <webElementGuid>4c27c223-0d48-4b5e-aaaf-527e06ea8269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
			                            
			                            Lowongan
			                        </value>
      <webElementGuid>f814ede4-a49a-4aaf-9610-c13d0c5b809d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;job_vacancy&quot;)/a[1]</value>
      <webElementGuid>87e789f0-0f62-4951-90be-f06ae3d4ae46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='job_vacancy']/a</value>
      <webElementGuid>28ded4e0-2956-489d-a004-baa0608b50a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lowongan']/parent::*</value>
      <webElementGuid>feae74f3-137a-46a8-b876-71bc617ef7ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'main#job_vacancy')]</value>
      <webElementGuid>536204a8-a8d6-4646-9617-8e625e325c66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>29fa5682-570c-4491-9ed5-f46d231c5799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'main#job_vacancy' and (text() = '
			                            
			                            Lowongan
			                        ' or . = '
			                            
			                            Lowongan
			                        ')]</value>
      <webElementGuid>03942195-b6c1-4309-a19a-17dcbeb5a719</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
