<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Lowongan_name_vacancy</name>
   <tag></tag>
   <elementGuidId>1faad82f-7c3d-49a2-bf7e-916b065ba6ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#name_vacancy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='name_vacancy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Cari kata kunci vacancy&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>37f6ec99-8168-4839-bf52-0cde9fb59ed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>96b118fe-e17d-442d-a255-d91a59cff964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1152b3c8-3aa5-4ebf-9e63-dc8fe04694e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name_vacancy</value>
      <webElementGuid>75f965b4-6255-459a-9a06-3c5cf2712d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>name_vacancy</value>
      <webElementGuid>d1b1c8d2-855a-4f19-b548-2e012b081808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari kata kunci vacancy</value>
      <webElementGuid>45a9f489-240a-46ce-93c3-3e50ba88931f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;name_vacancy&quot;)</value>
      <webElementGuid>b616347f-2da4-4dfd-9ec2-231d1544230f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='name_vacancy']</value>
      <webElementGuid>fb3350bd-b83c-4edf-9d6c-147ecbc78d0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content_col_4']/div/div[2]/div[2]/div/input</value>
      <webElementGuid>51fe23d1-632a-4279-a4a5-e09c9b52c258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>f4a65a3b-8b16-4aee-87b7-84eda0e4e601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'name_vacancy' and @id = 'name_vacancy' and @placeholder = 'Cari kata kunci vacancy']</value>
      <webElementGuid>f5ac76c3-ea95-4e45-bf10-a3935b5ee64d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
