<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_search</name>
   <tag></tag>
   <elementGuidId>608ef2eb-aa32-47ed-8e84-203ae45cf359</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.input-group-addon > span.material-icons</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content_col_4']/div/div[2]/div[2]/div/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#content_col_4 >> internal:text=&quot;search&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c171403c-df6e-420a-b610-462d5c32eb03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons</value>
      <webElementGuid>42337d1c-27a3-4f77-9be6-9537c4fad5d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>c22cd316-b1b3-4794-a913-c59716def314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content_col_4&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row fixme&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;input-group&quot;]/span[@class=&quot;input-group-addon&quot;]/span[@class=&quot;material-icons&quot;]</value>
      <webElementGuid>c754c6c6-9dac-4e37-a014-516a967a7b5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content_col_4']/div/div[2]/div[2]/div/span/span</value>
      <webElementGuid>0a3804fa-d8aa-4415-a815-e2467ac331f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Lowongan'])[1]/following::span[2]</value>
      <webElementGuid>75daf603-03f4-4178-a704-11aa0c5b96d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset'])[1]/following::span[2]</value>
      <webElementGuid>99217dfa-852f-4dfd-a577-fbb325317fbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama perusahaan'])[1]/preceding::span[1]</value>
      <webElementGuid>40179afc-d5d5-4e6e-bcc7-49ac36e8af5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bidang Pekerjaan'])[1]/preceding::span[5]</value>
      <webElementGuid>153dca7b-cd0c-43a5-8c41-9c56de0785f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='search']/parent::*</value>
      <webElementGuid>5d968b4d-44a8-409c-83b7-358cf4ea3240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>34a3564d-51d0-4e63-b00f-8428d2578a01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'search' or . = 'search')]</value>
      <webElementGuid>9f2a3b43-6cf2-4e8f-a7a1-d4109710b2bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
